project:
  type: website

website:
  title: "portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: index.qmd
        text: Home
      - projects.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

