project:
  type: website

website:
  title: "portfolio"
  navbar:
    left:
      - href: about.qmd
        text: About
    right:
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: source
execute: 
  freeze: true
