---
title: "My Post"
description: "Post description"
author: "Fizz McPhee"
date: "5/22/2021"
date-modified: "5/23/2021"
---



```{r}
# Option 1: tidytuesdayR package 
## install.packages("tidytuesdayR")
library(tidyverse)
tuesdata <- tidytuesdayR::tt_load('2023-08-22')
data_raw <- tuesdata |> pluck(1)
```

```{r}
df <- data_raw |> 
  mutate(year = as_date(parse_date_time(year, "%Y")), .before = 1)
```

# Focus

* how many refugees (refugees), what is the diff (asylum_seekers)
* from where (coo_name) to destination (coa_name)
* has it changed? why it has changed?

* too many countries, what to focus
  + changes in some region? - why a change has happended?
* short deep dive to asylum seekers?



```{r}
df |> count(coo_name, sort = T)
df |> count(coa_name, sort = T)

df |> count(coo_name,coa_name, sort = T)

```

# check egypt

```{r}
refugees_to_country <- df |> 
  group_by(coa_name, year = year(year)) |> 
  summarise(total_refugess = sum(refugees)) |>
  ungroup(year) |> 
  mutate(change = log(total_refugess) - log( (lag(total_refugess, order_by = year))))
refugees_to_country
```

```{r}
refugees_to_country |> 
  ggplot(aes(year, total_refugess)) + 
  geom_line() +
  scale_y_log10()
```


```{r}

df |> 
  ggplot(aes(year, refugees))+
  geom_col()

df |> 
  ggplot(aes(year, asylum_seekers))+
  geom_col()
```
